language: julia
os:
    - linux
    - osx
julia:
    - 1.0
    - 1.1
notifications:
    email: false
sudo: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'using InteractiveUtils; versioninfo(); using Pkg; Pkg.test("FactCheck", coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("FactCheck")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
